#!/usr/bin/env bash

DATE=$(date +"%d/%m/%Y")
CONTENT="BRADESCO CARTOES:COMPRA APROVADA NO CARTAO FINAL 9999 EM ${DATE} 13:46. VALOR DE $ 156,47 NO(A) GIASSI SUPERMERCADOS LOJAJOINVILLE"

echo "sms send 27888 ${CONTENT}" | nc localhost 5554
